name: Fetch & Translate

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch: {}      # lets you run it manually

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ingest/requirements.txt

      - name: Run ingest
        env:
          LIBRETRANSLATE_URL: "https://libretranslate.com/translate"
          TRANSLATE_SLEEP: "0.8"
        run: |
          python ingest/ingest_translate.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add site/data/articles.json
          if ! git diff --cached --quiet; then
            git commit -m "Update translated feed ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
          else
            echo "No changes to commit."
          fi
